# SPDX-FileCopyrightText: Copyright (c) 2026 Louis Gevers
# SPDX-License-Identifier: BSD-3-Clause
#
# See LICENSE file for full license information.
#
from typing import Protocol
from numpy.typing import ArrayLike

RNGKey = ArrayLike


class Backend(Protocol):
    name: str

    # constants
    pi: float

    # array ops
    def array(self, x): ...
    def zeros(self, shape): ...
    def ones(self, shape): ...
    def concatenate(self, xs, axis=0): ...
    def tile(self, xs, reps): ...
    def where(self, condition, x, y): ...
    def roll(self, x, shift): ...
    def clip(self, x, min, max): ...
    def norm(self, x, axis=None): ...
    def exp(self, x): ...
    def sin(self, x): ...
    def cos(self, x): ...
    def sum(self, x): ...
    def square(self, x): ...
    def abs(self, x): ...
    def any(self, x): ...
    def all(self, x): ...
    def isnan(self, x): ...
    def quat2euler(self, xyzw): ...
    def quat_rotate(self, xyzw, v, inverse: bool = False): ...

    # execution transforms
    def jit(self, fn, **kwargs): ...
    def scan(self, fn, init, xs, length): ...

    # RNG
    def rng_seed(self, seed: int) -> RNGKey: ...
    def rng_split(self, key: RNGKey, num: int = 2) -> tuple[RNGKey, ...]: ...
    def rng_uniform(
        self, key: RNGKey, shape: tuple[int, ...], minval=0.0, maxval=1.0
    ) -> ArrayLike: ...
    def rng_exponential(self, key: RNGKey, shape: tuple[int, ...]) -> ArrayLike: ...
    def rng_bernoulli(
        self, key: RNGKey, p: ArrayLike, shape: tuple[int, ...]
    ) -> ArrayLike: ...
    def rng_normal(
        self, key: RNGKey, shape: tuple[int, ...], mean=0.0, std=1.0
    ) -> ArrayLike: ...
