from typing import Protocol


class Backend(Protocol):
    name: str

    def array(self, x): ...
    def zeros(self, shape): ...
    def ones(self, shape): ...
    def concatenate(self, xs, axis=0): ...
    def clip(self, x, min, max): ...
    def norm(self, x, axis=None): ...
    def sin(self, x): ...
    def cos(self, x): ...
