# SPDX-FileCopyrightText: Copyright (c) 2026 Louis Gevers
# SPDX-License-Identifier: BSD-3-Clause
#
# See LICENSE file for full license information.
#
embodiment:
  type: go2

physics:
  type: mujoco
  mjcf: assets/mujoco/go2_flat_terrain.mjcf
  dt: 0.005

runtime:
  actuator_hz: 200
  policy_hz: 100

actuator:
  type: pd
  gain: 0.5
  kp: 55
  kd: 1

signals:
  # COMMANDS
  - type: resampled_uniform_value
    name: linear_velocity_command
    max_resample_duration: 5.0
    min_values: [-1.0, 0.5]
    max_values: [1.0, 0.5]
    p_nonzero: [0.9, 0.25]
  - type: resampled_uniform_value
    name: angular_velocity_command
    max_resample_duration: 5.0
    min_values: -1.0
    max_values: 1.0
    p_nonzero: 0.5
  # HISTORY
  - type: prev_action
    name: prev_action
  # FEET AIR TIME REWARD
  - type: feet_contact_signals
    name: feet_contact_signals

observations:
  - type: q
  - type: dq
  - type: gravity_vector
  - type: base_linear_vel
  - type: base_angular_vel
  - type: foot_contacts
  - type: linear_velocity_command
  - type: angular_velocity_command
  - type: prev_action

rewards:
  # Task rewards
  - type: linear_velocity_tracking
    weight: 1.0
    sensitivity: 0.25
  - type: angular_velocity_tracking
    weight: 0.5
    sensitivity: 0.25
  # Posture rewards
  - type: nominal_pose_tracking
    weight: 0.5
    sensitivity: 0.25
    q_weights: [1.0, 1.0, 0.0] # Only hip and knee
  # Penalties for motions in other DoFs
  - type: linear_velocity_penalty
    weight: -2.0
  - type: angular_velocity_penalty
    weight: -0.05
  # Penalties for regularization
  - type: action_regularization
    weight: -0.01
  - type: energy_penalty
    weight: -0.001
  # Penalties (naturalness)
  - type: contacts_penalty
    weight: -1.0
  - type: feet_air_time
    weight: 1.0
    min_time: 0.1

terminations:
  - type: has_nans
  - type: timeout
    max_duration: 20.0
  - type: fall
    min_height: 0.1
    max_angle: 1.57
  - type: contacts

metrics:
  - type: nominal_pose_tracking
    sensitivity: 0.25
    q_weights: [1.0, 1.0, 0.0] # Only hip and knee
  - type: linear_velocity_penalty
  - type: angular_velocity_penalty
  - type: action_regularization
  - type: energy_penalty
  - type: joint_torque_penalty
  - type: orientation_penalty
  - type: contacts_penalty
  - type: feet_air_time
    min_time: 0.0
  - type: joint_velocity_penalty
  - type: joint_acceleration_penalty
  - type: joint_torque_penalty

domain_randomization:
  - type: ground_friction
    min: 0.4
    max: 1.0
  - type: scale_masses
    min: 0.9
    max: 1.1
  - type: add_base_mass
    min: 0.0
    max: 5.0
  - type: initial_joint_offsets
    min: -0.2
    max: 0.2
  - type: push_robot
    interval: 15.0
    duration: 0.2
    max_velocity: 3.0
