embodiment:
  type: go2

physics:
  type: mujoco
  mjcf: assets/mujoco/go2.mjcf
  dt: 0.005

runtime:
  actuator_hz: 200
  policy_hz: 100

actuator:
  type: pd
  gain: 0.78
  kp: 30
  kd: 0.5

signals:
  - type: prev_action
    name: prev_action
  - type: episode_uniform_value
    name: velocity_command
    min_values:
      - 0.2
      - 0.0
    max_values:
      - 1.0
      - 0.0

observations:
  - type: q
  - type: dq
  - type: gravity_vector
  - type: base_linear_vel
  - type: base_angular_vel
  - type: foot_contacts
  - type: velocity_command
  - type: prev_action

rewards:
  - type: velocity_tracking
    weight: 1.0
    sensitivity: 0.25
  - type: action_regularization
    weight: -0.004

terminations:
  - type: has_nans
  - type: fall
    min_height: 0.1
    max_angle: 1.57
